# version: '3.8'

services:
  # Laravel-applicatie
  laravel_app:
    image: laravel_app
    build:
      context: ./laravelWebsite
      dockerfile: Dockerfile
    container_name: hospital_laravel
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./laravelWebsite/app/hospitalWebsite:/app:Z
    environment:
      - DB_HOST=db_laravel
      - DB_PORT=3306
      - DB_DATABASE=hospital_laravel_database
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravelPwd
    depends_on:
      - db_laravel
    networks:
      - hospital_network

  db_laravel:
    image: mariadb:10.6.19-focal
    container_name: hospital_laravel_db
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=hospital_laravel_database
      - MARIADB_USER=laravel
      - MARIADB_PASSWORD=laravelPwd
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - ./laravelWebsite/db_data:/var/lib/mysql:Z
    networks:
      - hospital_network

  # Microservices
  # User Profile Service
  user_profile_api:
    container_name: user_profile_api
    build:
      context: ./services/userProfileAPI/userProfileAPIService
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8002:5109"
    depends_on:
      - db_user_profile
    volumes:
      - ./services/userProfileAPI/userProfileAPIService:/app:Z
    networks:
      - hospital_network

  db_user_profile:
    container_name: db_user_profile
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_profile_database
    ports:
      - "5433:5432"
    volumes:
      - ./services/userProfileAPI/db_data:/var/lib/postgresql/data:Z
    networks:
      - hospital_network

  # Agenda Service
  agenda_api:
    container_name: agenda_api
    build:
      context: ./services/agendaAPI/agendaAPIService
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8082:8082"
    depends_on:
      - db_agenda
    volumes:
      - ./services/agendaAPI/agendaAPIService:/app:Z
    networks:
      - hospital_network

  db_agenda:
    container_name: db_agenda
    image: timescale/timescaledb:latest-pg12
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agenda_database
    ports:
      - "5434:5432"
    volumes:
      - ./services/agendaAPI/db_data:/var/lib/postgresql/data:Z
    networks:
      - hospital_network

  adminer:
    image: adminer:4.8.1-standalone
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - hospital_network

networks:
  hospital_network:
    driver: bridge