version: '3.8'

services:
  laravel_app:
    build:
      context: ./laravelWebsite
      dockerfile: Dockerfile
    container_name: hospital_laravel
    restart: unless-stopped
    ports:
      - "8000:8000"  # Expose de poort van de container naar de host
    volumes:
      - ./laravelWebsite/app/hospitalWebsite:/app  # Houd de Laravel-applicatie in sync
    environment:
      - DB_HOST=db_laravel
      - DB_PORT=3306
      - DB_DATABASE=hospital_laravel_database
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravelPwd
    depends_on:
      - db_laravel
    networks:
      - hospital_network

  db_laravel:
    image: mariadb:10.6.19-focal
    container_name: hospital_laravel_db
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=hospital_database
      - MARIADB_USER=laravel
      - MARIADB_PASSWORD=laravelPwd
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - ./laravelWebsite/db_data:/var/lib/mysql
    networks:
      - hospital_network

networks:
  hospital_network:
    driver: bridge
